### ISSUE TITLE
Multiple undefined variables

### ISSUE THREAD

**Issue by viralpoetry** [MaxHalford/xgp#1]
Hi,
I am trying to build the code from master, but have multiple errors due to undefined variables:
```
# github.com/MaxHalford/xgp
./program.go:35: prog.Tree.EvaluatePartial undefined (type tree.Tree has no field or method EvaluatePartial)
./program.go:45: prog.DRS.PredictPartial undefined (type *DynamicRangeSelection has no field or method PredictPartial)
./util.go:37: d.Round undefined (type time.Duration has no field or method Round)
```

I have installed those dependencies:
```
go get github.com/kniren/gota/dataframe
go get github.com/kniren/gota/series
go get github.com/mitchellh/go-homedir
go get github.com/spf13/viper
go get github.com/spf13/cobra
```

I am not sure if it is my ignorance, I have missed something, or whether the master branch is not complete.

Thanks for this promising project. I really appreciate it

**Comment by MaxHalford** [comment]
Hey,

These errors:

```sh
./program.go:35: prog.Tree.EvaluatePartial undefined (type tree.Tree has no field or method EvaluatePartial)
./program.go:45: prog.DRS.PredictPartial undefined (type *DynamicRangeSelection has no field or method PredictPartial)
```

are my bad, I just fixed them in the last commit.

However the last one:

```sh
./util.go:37: d.Round undefined (type time.Duration has no field or method Round)
```

is probably because your Go version is too old. I've been running tests with Go 1.9, how about you?

Thanks for the kind words, most of the hard work is done but I have to wrap it up and finish the documentation.

**Comment by viralpoetry** [comment]
Old version of `go` was the case. Thx for pointing out.
